const express = require('express')
const router = express.Router()

// Test Routes
router.use('/test', require('./testRoutes'))

// Routes
router.use('/role-permissions', require('./rolePermissionsRoutes'))
router.use('/auth', require('./authRoutes'))
router.use('/user', require('./userRoutes'))
router.use('/admins', require('./adminRoutes'))
router.use('/rooms', require('./roomRoutes'))
router.use('/groups', require('./groupRoutes'))
router.use('/teachers', require('./teacherRoutes'))
router.use('/staffs', require('./staffRoutes'))
router.use('/students', require('./studentRoutes'))
router.use('/student-fees', require('./studentFeesRoutes'))
router.use('/classes', require('./classRoutes'))
router.use('/subjects', require('./subjectRoutes'))
router.use('/sections', require('./sectionRoutes'))
router.use('/notices', require('./noticeRoutes'))
router.use('/attendance', require('./attendanceRoutes'))
router.use('/class-attendance', require('./classAttendanceRoutes'))
router.use('/class-routines', require('./classRoutineRoutes'))
router.use('/exam-categories', require('./examCategoryRoutes'))
router.use('/exams', require('./examRoutes'))
router.use('/exam-results', require('./examResultRoutes'))
router.use('/grades', require('./gradingRoutes'))
router.use('/designations', require('./designationRoutes'))
router.use('/expense-categories', require('./expenseCategoryRoutes'))
router.use('/expenses', require('./expenseRoutes'))
router.use('/salaries', require('./salaryRoutes'))
router.use('/teacher-assignments', require('./teacherAssignmentRoutes'))
router.use('/teacher-notices', require('./teacherNoticeRoutes'))
router.use('/homeworks', require('./studentHomeworkRoutes'))
router.use('/applications', require('./applicationRoutes'))
router.use('/todos', require('./todoRoutes'))

// Website Routes
router.use('/hero-section', require('./heroSectionRoutes'))
router.use('/chairman-section', require('./chairmanSectionRoutes'))
router.use('/contact', require('./contactRoutes'))
router.use('/about', require('./aboutRoutes'))
router.use('/social', require('./socialRoutes'))
router.use('/events', require('./eventRoutes'))
router.use('/photo-gallery', require('./photoGalleryRoutes'))
router.use('/information', require('./informationRoutes'))
router.use('/shift', require('./shiftRoutes'))

module.exports = router
